[package]
name = "commit-boost"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-cli.workspace = true
cb-common.workspace = true
cb-pbs.workspace = true
cb-crypto.workspace = true

tokio.workspace = true
async-trait.workspace = true

serde_json.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

clap.workspace = true


[[bin]]
name = "commit-boost"
path = "commit_boost.rs"

[[bin]]
name = "default-pbs"
path = "default_pbs.rs"

[[bin]]
name = "signer-module"
path = "signer_module.rs"
