chain = "Holesky"

[pbs]
# path = "target/debug/custom_boost"
address = "commit-boost:18551"
relays = []
relay_check = true
timeout_get_header_ms = 950
timeout_get_payload_ms = 4000
timeout_register_validator_ms = 3000
skip_sigverify = true
min_bid_eth = 0.0

[signer]
address = "commit-boost:33951"
[signer.loader]
key_path = "keys.example.json"

[metrics]
address = "commit-boost:13030"
jwt_path = "metrics_jwt.txt"

# [[modules]]
# id = "DA_COMMIT"
# path = "target/debug/da_commit"
# sleep_secs = 5

[[modules]]
id = "DA_COMMIT"
docker_image="da_commit"
sleep_secs = 5