version: '3.7'

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    platform: linux/amd64
    ports:
      - "9090:9090"
    network_mode: "host"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
