version: '3'

services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    platform: linux/amd64
    ports:
      - "9090:9090" # Only in case we'd want to inspect this in the browser, otherwise not needed
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
