version: '3'

services:
  commit-boost:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "13030:13030"
    # NOTE:
    #  Mount the local machine's docker socket file to the container, so that CB can start sibling containers (the modules)
    #  on the same docker engine using its API
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - monitoring

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    platform: linux/amd64
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
