[package]
name = "commit-boost"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-cli.workspace = true
cb-common.workspace = true
cb-pbs.workspace = true


tokio.workspace = true
async-trait.workspace = true

serde_json.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

clap.workspace = true
